dist: xenial
language: python
before_install:
- export TZ=america/new-york
- openssl aes-256-cbc -K $encrypted_2f5e3e66b395_key -iv $encrypted_2f5e3e66b395_iv
  -in firestore_creds.json.enc -out ./src/firestore_creds.json -d
install:
- pip install -r requirements.txt
jobs:
  include:
    - stage: Python3.6
      python: '3.6'
      script:
        - cd ./src/tests && python src/tests/test-calendar_actions.py
        - cd ./src/tests && python src/tests/test-database.py
        - cd ./src/tests && python src/tests/test-utils-datetime_utils.py
        - cd ./src/tests && python src/tests/test-utils-generic.py
    - stage: Python3.7
      python: '3.7'
      script:
        - cd ./src/tests && python src/tests/test-calendar_actions.py
        - cd ./src/tests && python src/tests/test-database.py
        - cd ./src/tests && python src/tests/test-utils-datetime_utils.py
        - cd ./src/tests && python src/tests/test-utils-generic.py
    - stage: Python3.7-dev
      python: 3.7-dev
      script:
        - cd ./src/tests && python src/tests/test-calendar_actions.py
        - cd ./src/tests && python src/tests/test-database.py
        - cd ./src/tests && python src/tests/test-utils-datetime_utils.py
        - cd ./src/tests && python src/tests/test-utils-generic.py
stages:
  - Python3.6
  - Python3.7
  - Python3.7-dev