dist: xenial
language: python
python:
- '3.6'
- '3.7'
- 3.7-dev
- 3.8-dev
install:
- pip install -r travis_requirements.txt
script:
- python src/test-calendar_actions.py
- python test-utils-generic.py
- python test-utils-datetime_utils.py
- find ./ -type f
before_install:
- openssl aes-256-cbc -K $encrypted_2f5e3e66b395_key -iv $encrypted_2f5e3e66b395_iv
  -in firestore_creds.json.enc -out ./src/firestore_creds.json -d
