dist: xenial
before_install:
  - export TZ=america/new-york
  - echo $firebase_creds >> src/tests/firestore_creds.json
jobs:
  include:
    - stage: Python
      language: python
      python:
        - 3.6
        - 3.7
        - 3.7-dev
      install: pip install -r requirements.txt
      script:
        - cd src/tests
        - pytest --emoji
    - stage: Docker
      language: generic
      services: docker
      script:
        - docker build -f Dockerfile.dev -t mattgleich/server-monitor:latest .
        - docker run -e CI=true mattgleich/server-monitor
stages:
  - Python
  - Docker
