dist: xenial
language: python
python:
    - "3.6"
    - "3.7"
install:
    - pip install -r travis_requirements.txt
script: 
    - python src/test-calendar_actions.py
    - python test-utils-generic.py
    - python test-utils-datetime_utils.py
