name: Docker-Cron
on:
  schedule:
    - cron:  '0 * * * *'
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Piping Secrets
        run: |
          echo ${{ secrets.firebase_creds }} >> src/secrets/firestore_creds.json
          echo ${{ secrets.firebase_creds }} >> tests/firestore_creds.json
      - name: Building and Testing Production Image
        run: |
          docker-compose up -d
          sleep 15
          docker-compose down
