name: Docker
on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Piping Secrets
        run: |
          echo ${{ secrets.firebase_creds }} >> tests/firestore_creds.json
      - name: Building Image
        run: |
          docker build -f dev.Dockerfile -t ghsapp/scrape-calendar-data:dev .
      - name: Testing Image
        run: |
          docker run -e CI=true ghsapp/scrape-calendar-data:dev
      - name: Building and Testing Production Image
        run: |
          docker-compose up -d
          sleep 15
          docker-compose down
