name: Docker-Hub 
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.docker_password }} | docker login -u ${{ secrets.docker_id }} --password-stdin
      - name: Building Production Image
        run: |
          docker build -t ghsapp/scrape-calendar-data .
      - name: Testing Production Image
        run: |
          echo ${{ secrets.firebase_creds }} >> src/secrets/firestore_creds.json
          docker-compose up -d
          sleep 15
          docker-compose down
      - name: Pushing to Docker Hub
        run: |
          docker push ghsapp/scrape-calendar-data
