name: Docker-Cron
on:
  schedule:
    - cron:  '0 * * * *'
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Piping Secrets
        run: |
          echo ${{ secrets.firebase_creds }} >> src/secrets/firestore_creds.json
          echo ${{ secrets.firebase_creds }} >> tests/firestore_creds.json
      - name: Building Image
        run: |
          docker build -f dev.Dockerfile -t ghsapp/scrape-calendar-data:latest .
      - name: Testing Image
        run: |
          docker run -v /src/secrets:/src/secrets -e CI=true ghsapp/scrape-calendar-data
      - name: Building and Testing Production Image
        run: |
          docker-compose up -d
          sleep 15
          docker-compose down
