name: Python-Versions
on: [push, pull_request, release]

jobs:
  test:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python: ["3.6", "3.7", "3.7-dev"]

    steps:
    - uses: actions/checkout@v1
    - name: Piping Secrets
      run: |
        echo ${{ secrets.firebase_creds }} >> src/tests/firestore_creds.json
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        cd src/tests
        pytest --emoji
